- hosts: haproxy
  become: true
  become_method: sudo
  vars:
    mode: docker

  tasks:
    - name: Install apt-python
      raw: "[ -x /usr/bin/python ] || apt update && apt install -y python-apt"

    - name: Install required packages
      apt:
        pkg:
          - wget
          - unzip
          - gnupg2
          - apt-transport-https
          - ca-certificates
          - haproxy
          - python-pip
        state: present

    - name: Ensure required directories
      file:
        path: "{{ nomad_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes
      loop_control:
        loop_var: nomad_dir
      with_items:
        - /etc/consul
        - /etc/vault
        - /opt/consul
        - /opt/consul/bin
        - /opt/consul/etc/templates
        - /var/lib/vault

    - name: Download and extract vault
      shell: |
        mkdir -p /opt/vault/bin /opt/vault/etc/policies
        cd /opt/vault/bin
        wget https://releases.hashicorp.com/vault/1.6.0/vault_1.6.0_linux_amd64.zip
        unzip *.zip
        chmod 755 vault
        rm -fr *.zip
      args:
        creates: /opt/vault/bin/vault

    - name: Ensure vault configuration
      template:
        src: "templates/vault.hcl"
        dest: "/etc/vault/vault.hcl"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Ensure vault service definition
      template:
        src: "templates/vault.service"
        dest: "/etc/systemd/system/vault.service"
        owner: root
        group: root
        mode: 0644
      register: vault_service

    - name: Ensure vault post-start file
      copy:
        src: "files/post-start"
        dest: "/opt/vault/bin/post-start"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: Copy frontend vault policies
      copy:
        src: "vault/{{ vault_policy }}.hcl"
        dest: "/opt/vault/etc/policies/{{ vault_policy }}.hcl"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - frontend
      loop_control:
        loop_var: vault_policy

    - name: Reload systemd
      shell: systemctl daemon-reload
      when: vault_service.changed

    - name: Ensure vault service is running
      service:
        name: vault
        state: started
      register: vault_service

    - name: Download and extract consul
      shell: |
        cd /opt/consul/bin
        wget https://releases.hashicorp.com/consul/1.9.0/consul_1.9.0_linux_amd64.zip
        unzip *.zip
        rm -fr *.zip
      args:
        creates: /opt/consul/bin/consul

    - name: Download and extract consul-template
      shell: |
        cd /opt/consul/bin
        wget https://releases.hashicorp.com/consul-template/0.25.1/consul-template_0.25.1_linux_amd64.zip
        unzip *.zip
        rm -fr *.zip
      args:
        creates: /opt/consul/bin/consul-template

    - name: Ensure files are executable
      file:
        path: "{{ nomad_binary }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - /opt/consul/bin/consul
        - /opt/consul/bin/consul-template
      loop_control:
        loop_var: nomad_binary

    - name: Ensure consul agent service
      template:
        src: "templates/consul-agent.service"
        dest: "/etc/systemd/system/consul-agent.service"
        owner: root
        group: root
        mode: 0644
      register: consul_agent_service

    - name: Ensure consul template service
      template:
        src: "templates/consul-template.service"
        dest: "/etc/systemd/system/consul-template.service"
        owner: root
        group: root
        mode: 0644
      register: consul_template_service

    - name: Reload systemd
      shell: systemctl daemon-reload
      when: consul_template_service.changed or consul_agent_service.changed or vault_service.changed

    - name: Ensure haproxy consul template
      copy:
        src: files/haproxy.cfg.tpl
        dest: /opt/consul/etc/templates/haproxy.cfg.tpl
        owner: root
        group: root
        mode: 0644

    - name: Ensure consul-agent is running
      service:
        name: consul-agent
        state: started
        enabled: yes

    - name: Ensure consul template is running
      service:
        name: consul-template
        state: started
        enabled: yes
      
    - name: Ensure happroxy is stopped and disabled
      service:
        name: haproxy
        state: stopped
        enabled: no


